
const LoremIpsum =()=>{
    return (<>
        <div>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Duis ultricies lacus sed turpis tincidunt id aliquet risus feugiat. Cursus turpis massa tincidunt dui ut ornare. Risus at ultrices mi tempus imperdiet nulla malesuada. Curabitur vitae nunc sed velit dignissim. Ut aliquam purus sit amet luctus venenatis lectus. Id porta nibh venenatis cras sed felis eget velit. Ipsum suspendisse ultrices gravida dictum fusce ut. Urna id volutpat lacus laoreet non. Euismod quis viverra nibh cras pulvinar mattis nunc sed blandit. Massa eget egestas purus viverra accumsan in nisl. Nunc pulvinar sapien et ligula ullamcorper malesuada proin libero. Facilisis volutpat est velit egestas dui id. Convallis tellus id interdum velit.</p>
            <p>Elit sed vulputate mi sit amet mauris. Neque ornare aenean euismod elementum nisi. Leo duis ut diam quam nulla porttitor massa. Mattis nunc sed blandit libero volutpat sed cras ornare arcu. Gravida dictum fusce ut placerat orci. Posuere lorem ipsum dolor sit amet. Mi in nulla posuere sollicitudin aliquam ultrices sagittis orci a. Aliquam sem et tortor consequat. Velit euismod in pellentesque massa placerat duis ultricies lacus sed. At in tellus integer feugiat. Ullamcorper malesuada proin libero nunc consequat interdum varius.</p>
            <p>Pulvinar neque laoreet suspendisse interdum consectetur libero. Donec et odio pellentesque diam volutpat commodo sed egestas egestas. Cursus metus aliquam eleifend mi in nulla posuere sollicitudin aliquam. Justo laoreet sit amet cursus sit. Ligula ullamcorper malesuada proin libero nunc consequat interdum varius sit. Nam at lectus urna duis convallis convallis. Ipsum dolor sit amet consectetur. Ultricies mi eget mauris pharetra. Neque volutpat ac tincidunt vitae semper quis. Nullam vehicula ipsum a arcu cursus vitae congue. Convallis a cras semper auctor. In iaculis nunc sed augue lacus viverra vitae congue eu. Elit pellentesque habitant morbi tristique senectus et netus. Aliquam sem et tortor consequat id porta nibh venenatis. Pulvinar sapien et ligula ullamcorper malesuada.</p>
            <p>Sagittis nisl rhoncus mattis rhoncus urna. Leo vel fringilla est ullamcorper eget nulla facilisi etiam dignissim. Id diam vel quam elementum pulvinar etiam non. Et odio pellentesque diam volutpat commodo sed egestas. Consectetur adipiscing elit duis tristique sollicitudin. Turpis massa sed elementum tempus egestas sed sed. Tincidunt tortor aliquam nulla facilisi cras. Volutpat commodo sed egestas egestas fringilla phasellus. Proin fermentum leo vel orci porta non pulvinar neque laoreet. Amet nulla facilisi morbi tempus iaculis urna. Consequat nisl vel pretium lectus quam id leo in vitae. Egestas sed sed risus pretium quam. Luctus accumsan tortor posuere ac ut consequat.</p>
            <p>Egestas diam in arcu cursus euismod. Odio eu feugiat pretium nibh ipsum consequat nisl vel. Leo a diam sollicitudin tempor id. Varius vel pharetra vel turpis nunc eget lorem. Et malesuada fames ac turpis egestas sed tempus urna et. A diam maecenas sed enim ut sem. Cras sed felis eget velit aliquet sagittis id consectetur purus. Nam libero justo laoreet sit amet cursus. Proin sagittis nisl rhoncus mattis rhoncus urna. Massa id neque aliquam vestibulum morbi blandit cursus. Cras ornare arcu dui vivamus arcu felis. Et ligula ullamcorper malesuada proin libero nunc consequat interdum varius. Amet aliquam id diam maecenas ultricies mi. Non odio euismod lacinia at quis risus. Massa eget egestas purus viverra accumsan in nisl nisi scelerisque. Ultrices tincidunt arcu non sodales neque sodales. Pretium fusce id velit ut tortor pretium viverra suspendisse potenti. Nunc mi ipsum faucibus vitae aliquet nec ullamcorper sit. Volutpat est velit egestas dui. Maecenas accumsan lacus vel facilisis volutpat est velit egestas dui.</p>
        </div>
    </>)
}

export default LoremIpsum;